# $Id: $(MAKEFILE),v 1.5 2008/09/19 22:06:47 shepperd Exp $

#    $(MAKEFILE).common - build rules for making macxx, a cross assembler family for various micro-processors
#    Copyright (C) 2008 David Shepperd
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#

CORE0 = symbol.o hashit.o memmgt.o dumdir.o dummy.o opcnds.o err2str.o add_defs.o utils.o
CORE1 = debug.o help.o 
CORE2 = macxx.o gc_table.o gc.o opcode.o
CORE3 = endlin.o outx.o pass2.o macros.o psuedo_ops.o
CORE4 = listctrl.o sortsym.o stack_ops.o qksort.o
EXPx  = le_itfc.o lib_exprs.o
PASSx = pass0.o pass1.o
MOST = $(CORE0) $(CORE1) $(CORE2) $(CORE3) $(CORE4)

ALLO65   = exprs65.o char_tbl65.o opc65.o pst65.o             $(MOST) $(PASSx) $(EXPx)
ALLO68   = exprs68.o char_tbl65.o opc68.o pst68.o             $(MOST) $(PASSx) $(EXPx)
ALLO69   = exprs69.o char_tbl65.o opc69.o pst69.o             $(MOST) $(PASSx) $(EXPx)
ALLO11   = exprs11.o char_tbl65.o opc11.o pst11.o m11types.o  $(MOST) $(PASSx) $(EXPx)
ALLO8080 = exprs.o char_table.o opc8080.o pst8080.o           $(MOST) $(PASSx) $(EXPx)
ALLOAS   = exprs.o char_table.o opcas.o pstas.o dummy_pass0.o pass1.o $(MOST) $(EXPx)
ALLOTJ   = exprs.o char_table.o opctj.o psttj.o dummy_pass0.o pass1.o $(MOST) $(EXPx)
ALLO68K  = exprs68k.o char_table.o opc68k.o pst68k.o m68types.o dummy_pass0.o pass168k.o $(MOST)

ALLOPP0 = macxx_pp.o pass1_pp.o lstctlpp.o opcode_pp.o
ALLOPP1 = gc_tblpp.o gc_pp.o exprs_pp.o macros_pp.o
ALLOPP2 = psdo_ops_pp.o pstpp.o opcpp.o char_table.o
ALLOPP3 = help_pp.o $(CORE0)

ALLH = structs.h header.h ct.h token_defs.h token.h

HERE = ./
EXE =
ifeq ($(MINGW),1)
	EXE = .exe
	HERE = .\\
endif
ifeq ($(MSYS2),1)
	EXE = .exe
endif

# For Generic Unix/x86
DEFINES = -DEXTERNAL_PACKED_STRUCTS -DM_UNIX -DINCLUDE_FLOAT -DNO_XREF -DGCC -DHAS_STRERROR -D_ISOC99_SOURCE #-DPC_DEBUG #-DMAX_LINE_ERRORS=12 #-DDEBUG_TXT_INP
DEFINES += $(EXTRA_DEFINES)
CHKS = -Wall -ansi -pedantic -Wno-char-subscripts #-std=c99
CHKS += $(EXTRA_CHKS)
CFLAGS = $(OPT) $(DBG) $(DEFINES) $(HOST_CPU) -I. $(CHKS)
L = $(CC) $(HOST_CPU)
C = $(CC) -c $(CFLAGS) 
MAKEFILE = Makefile.common

.SILENT:

ifeq ($(MINGW),1)

%.o : %.c
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -o $@ $<
else

%.o : %.c
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM);\
	rm -f $(basename $@).err $(basename $@).warn;\
	$C -o $@ $< > $(basename $@).err 2>&1;\
	if [ $$? -ne 0 ]; then\
	    $(ECHO) $(DELIM)Errors in $(basename $@).err$(DELIM);\
	    cat $(basename $@).err;\
	else\
	    if [ -s $(basename $@).err ]; then\
	        mv $(basename $@).err $(basename $@).warn;\
	        $(ECHO) $(DELIM)Warnings in $(basename $@).warn$(DELIM);\
	        cat $(basename $@).warn;\
            else\
	        rm -f $(basename $@).err;\
	    fi;\
	fi

endif    

%.E : %.c
	$(ECHO) $(DELIM)    Compiling $< to $@ ...$(DELIM)
	$(CC) $(CFLAGS) -E $< > $@

all : macas$(EXE) mac65$(EXE) mac68$(EXE) mac68k$(EXE) mac69$(EXE) macpp$(EXE) mactj$(EXE) mac11$(EXE) mac8080$(EXE)
	$(ECHO) $(DELIM)    Done$(DELIM)

define link_it
	$(ECHO) $(DELIM)    linking $@...$(DELIM)
	$L $(DBG) -o $@ $(filter-out $(MAKEFILE),$^)
endef

macpp$(EXE) : $(MAKEFILE) $(ALLOPP0) $(ALLOPP1) $(ALLOPP2) $(ALLOPP3) 
	$(link_it)

mactj$(EXE) : $(MAKEFILE) $(ALLOTJ) 
	$(link_it)

mac8080$(EXE) : $(MAKEFILE) $(ALLO8080) 
	$(link_it)

mac65$(EXE) : $(MAKEFILE) $(ALLO65) 
	$(link_it)

mac68$(EXE):  $(MAKEFILE) $(ALLO68)
	$(link_it)

mac68k$(EXE) : $(MAKEFILE) $(ALLO68K) 
	$(link_it)

mac69$(EXE):  $(MAKEFILE) $(ALLO69)
	$(link_it)

macas$(EXE) : $(MAKEFILE) $(ALLOAS) 
	$(link_it)

mac11$(EXE) : $(MAKEFILE) $(ALLO11)
	$(link_it)

dmpod$(EXE) : dmpod.o
	$(link_it)

gc_pp.o : gc.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h \
  qual_tbl.h gc_struct.h 
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -DMAC_PP -o $@ $<

gc_tblpp.o : gc_table.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h \
  ct.h qual_tbl.h gc_struct.h 
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -DMAC_PP -o $@ $<

help_pp.o : help.c add_defs.h 
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -DMAC_PP -o $@ $<

lstctlpp.o : listctrl.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h \
  qual_tbl.h listctrl.h lstcnsts.h exproper.h
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -DMAC_PP -o $@ $<

macxx_pp.o : macxx.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h \
  ct.h qual_tbl.h version.h strsub.h
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -DMAC_PP -o $@ $<

macros_pp.o : macros.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h \
  qual_tbl.h pst_tokens.h pst_structs.h listctrl.h lstcnsts.h 
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -DMAC_PP -o $@ $<

memmgt.o : memmgt.c 
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -DMACXX -o $@ $<

opcode_pp.o : opcode.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h \
  qual_tbl.h pst_tokens.h pst_structs.h 
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -DMAC_PP -o $@ $<

pass1_pp.o : pass1.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h \
  qual_tbl.h pst_tokens.h pst_structs.h listctrl.h lstcnsts.h strsub.h exproper.h
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -DMAC_PP -o $@ $<

psdo_ops_pp.o : psuedo_ops.c add_defs.h token.h token_defs.h structs.h header.h memmgt.h ct.h \
  qual_tbl.h pst_tokens.h pst_structs.h exproper.h listctrl.h lstcnsts.h strsub.h \
  opcnds.h 
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -DMAC_PP -o $@ $<

exprs65.o : exprs.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  exproper.h listctrl.h lstcnsts.h operstuff.h
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -DMAC_65 -o $@ $<

exprs11.o : exprs.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  exproper.h listctrl.h lstcnsts.h operstuff.h
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -DMAC_11 -o $@ $<

exprs68.o : exprs.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  exproper.h listctrl.h lstcnsts.h operstuff.h
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -DMAC_68 -o $@ $<

exprs68k.o : exprs.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  exproper.h listctrl.h lstcnsts.h operstuff.h
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -DMAC_68K -o $@ $<

exprs69.o : exprs.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  exproper.h listctrl.h lstcnsts.h operstuff.h
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -DMAC_69 -o $@ $<

exprs_pp.o : exprs.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  exproper.h listctrl.h lstcnsts.h operstuff.h
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -DMAC_PP -o $@ $<

mk_operstuff.o : mk_operstuff.c Makefile.common
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -o $@ $<

mk_operstuff$(EXE) : mk_operstuff.o Makefile.common
	$(link_it)

operstuff.h : operstuff.dat mk_operstuff$(EXE) Makefile.common
	$(ECHO) $(DELIM)    Making $@ ...$(DELIM)
	$(HERE)mk_operstuff > $@

lib_exprs.o : lib_exprs.c lib_exprs.h operstuff.h
	$(ECHO) $(DELIM)    Compiling $< ...$(DELIM)
	$C -D_FMT_LD_='"%d"' -DNO_FLOATING_POINT -o $@ $<

pass168k.o : pass1.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  pst_tokens.h pst_structs.h listctrl.h lstcnsts.h strsub.h exproper.h
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -DMAC_68K -o $@ $<

pass18080.o : pass1.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  pst_tokens.h pst_structs.h listctrl.h lstcnsts.h strsub.h exproper.h
	$(ECHO) $(DELIM)    Compiling $<...$(DELIM)
	$C -DMAC_8080 -o $@ $<

.PHONY: clean show

clean :
	$(ECHO) $(DELIM)    Cleaning ...$(DELIM)
	$(RM) mac65$(EXE) mac68$(EXE) mac69$(EXE) macas$(EXE) mac68k$(EXE) macpp$(EXE) mactj$(EXE) mac8080$(EXE) mac11$(EXE) mk_operstuff$(EXE) operstuff.h *.o *.b *.d *.E 

show :
	$(ECHO) $(DELIM) ALLO65   = $(ALLO65) $(DELIM)
	$(ECHO) $(DELIM) ALLO68   = $(ALLO68) $(DELIM)
	$(ECHO) $(DELIM) ALLO69   = $(ALLO69) $(DELIM)
	$(ECHO) $(DELIM) ALLO11   = $(ALLO11) $(DELIM)
	$(ECHO) $(DELIM) ALLO8080 = $(ALLO8080) $(DELIM)
	$(ECHO) $(DELIM) ALLOAS   = $(ALLOAS) $(DELIM)
	$(ECHO) $(DELIM) ALLOTJ   = $(ALLOTJ) $(DELIM)
	$(ECHO) $(DELIM) ALLO68K  = $(ALLO68K) $(DELIM)
	$(ECHO) $(DELIM) ALLOPP   = $(ALLOPP) $(DELIM)

add_defs.o : add_defs.c add_defs.h
char_table.o : char_table.c ct.h 
char_tbl65.o : char_tbl65.c ct.h 
debug.o : debug.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  debug.h stab.h stab.def segdef.h 
dmpgdb.o : dmpgdb.c symseg.h 
dmpod.o : dmpod.c debug.h stab.h stab.def segdef.h 
dumdir.o : dumdir.c 
dummy.o : dummy.c
dummy_pass0.o : dummy_pass0.c
edits.o : edits.c 
endlin.o : endlin.c header.h outx.h token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  listctrl.h lstcnsts.h exproper.h vlda_structs.h pragma.h pragma1.h segdef.h
err2str.o : err2str.c  
exprs.o : exprs.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  exproper.h listctrl.h lstcnsts.h operstuff.h
gc.o : gc.c  token.h token_defs.h header.h memmgt.h ct.h qual_tbl.h gc_struct.h 
gc_table.o : gc_table.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h \
  qual_tbl.h gc_struct.h 
gdbtst.o : gdbtst.c 
gototst.o : gototst.c 
hashit.o : hashit.c 
help.o : help.c add_defs.h 
listctrl.o : listctrl.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h \
  qual_tbl.h listctrl.h lstcnsts.h utils.h
le_itfc.o : le_itfc.c lib_exprs.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h \
   ct.h qual_tbl.h exproper.h listctrl.h lstcnsts.h lib_exprs.h le_itfc.h operstuff.h
m11types.o : m11types.c token.h \
  token_defs.h structs.h add_defs.h header.h memmgt.h ct.h \
  qual_tbl.h pdp11.h exproper.h listctrl.h lstcnsts.h pst_tokens.h pst_structs.h 
m68types.o : m68types.c token.h token_defs.h \
  structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  m68k.h exproper.h listctrl.h lstcnsts.h pst_tokens.h pst_structs.h 
macros.o : macros.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  pst_tokens.h pst_structs.h listctrl.h lstcnsts.h utils.h
macxx.o : macxx.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h \
  ct.h qual_tbl.h version.h  strsub.h listctrl.h
opc11.o : opc11.c token.h token_defs.h pst_tokens.h pst_structs.h exproper.h \
  structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  pst_tokens.h pst_structs.h exproper.h listctrl.h lstcnsts.h pdp11.h opcommon.h 
opc65.o : opc65.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  pst_tokens.h pst_structs.h exproper.h listctrl.h lstcnsts.h psttkn65.h opcommon.h 
opc68.o : opc68.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  pst_tokens.h pst_structs.h exproper.h listctrl.h lstcnsts.h psttkn68.h opcommon.h 
opc68k.o : opc68k.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  pst_tokens.h pst_structs.h exproper.h listctrl.h lstcnsts.h m68k.h opcommon.h 
opc69.o : opc69.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  pst_tokens.h pst_structs.h exproper.h listctrl.h lstcnsts.h psttkn69.h opcommon.h
opcas.o : opcas.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  pst_tokens.h pst_structs.h exproper.h listctrl.h lstcnsts.h op_class.h opcommon.h 
opcnds.o : opcnds.c opcnds.h 
opcode.o : opcode.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  pst_tokens.h pst_structs.h 
opcpp.o : opcpp.c lstcnsts.h pst_tokens.h pst_structs.h opcommon.h memmgt.h 
opctj.o : opctj.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  pst_tokens.h pst_structs.h exproper.h listctrl.h lstcnsts.h tjop_class.h opcommon.h 
outx.o : outx.c outx.h token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  vlda_structs.h pragma1.h segdef.h \
  pragma.h exproper.h 
pass0.o : pass0.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  pst_tokens.h pst_structs.h listctrl.h lstcnsts.h strsub.h exproper.h
pass1.o : pass1.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  pst_tokens.h pst_structs.h listctrl.h lstcnsts.h strsub.h exproper.h
pass2.o : pass2.c outx.h token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  vlda_structs.h pragma1.h segdef.h pragma.h vlda_structs.h 
pst11.o : pst11.c pst_tokens.h pst_structs.h pdp11.h opcs11.h dirdefs.h 
pst65.o : pst65.c pst_tokens.h pst_structs.h psttkn65.h dirdefs.h 
pst68.o : pst68.c pst_tokens.h pst_structs.h psttkn68.h dirdefs.h 
pst68k.o : pst68k.c pst_tokens.h pst_structs.h dirdefs.h opcs68k.h 
pst69.o : pst69.c pst_tokens.h pst_structs.h psttkn69.h dirdefs.h
#pst816.o : pst816.c pst_tokens.h pst_structs.h psttkn65.h dirdefs.h 
pstas.o : pstas.c pst_tokens.h pst_structs.h dirdefs.h asap_ops.h op_class.h 
pstpp.o : pstpp.c pst_tokens.h pst_structs.h dirdefs.h 
psttj.o : psttj.c pst_tokens.h pst_structs.h dirdefs.h tjop_class.h tj_ops.h 
psuedo_ops.o : psuedo_ops.c add_defs.h token.h token_defs.h structs.h header.h memmgt.h ct.h \
  qual_tbl.h pst_tokens.h pst_structs.h exproper.h listctrl.h lstcnsts.h strsub.h opcnds.h utils.h
qksort.o : qksort.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h 
sortsym.o : sortsym.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  listctrl.h lstcnsts.h 
stack_ops.o : stack_ops.c add_defs.h token.h token_defs.h structs.h header.h memmgt.h ct.h \
  qual_tbl.h pst_tokens.h pst_structs.h exproper.h listctrl.h lstcnsts.h strsub.h opcnds.h 
symbol.o : symbol.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h 
test.o : test.c token.h token_defs.h structs.h add_defs.h header.h memmgt.h ct.h qual_tbl.h \
  pst_tokens.h pst_structs.h listctrl.h lstcnsts.h 
tjtst.o : tjtst.c tjop_class.h tj_ops.h 
types.o : types.c stab.def
utils.o : utils.c utils.h
