# This is for a MinGW system running on Windows. Last checked on Windows 11.

HOST_CPU = 
DELIM = ^
PiOS32 = 1
LINUX = 0
MSYS2 = 0
MINGW = 1
EXTRA_DEFINES = -DMINGW
EXTRA_CHKS =
DBG = 
OPT = -O2
CC = mingw32-gcc
ECHO = echo
RM = CMD /C DEL /Q/S
RMDIR = CMD /C RMDIR /Q/S

include Makefile.common

