# This is for a generic Linux build
# For now, macxx has to be built to run in 32 bit mode.

HOST_CPU = -m32
DELIM = '
PiOS32 = 1
LINUX = 1
MSYS2 = 0
MINGW = 0
EXTRA_DEFINES = #-DNEW_ASCII_COMMON=0
EXTRA_CHKS =
DBG = -g
OPT = #-O2
CC = gcc
ECHO = /bin/echo -e
RM = rm -f 

include Makefile.common

