# This is for either a 32 or 64 bit PiOS version (Debian 32 bit on a Raspberry Pi). Only test on a Pi5.

HOST_CPU = 
DELIM = '
PiOS32 = 1
LINUX = 1
MSYS2 = 0
MINGW = 0
EXTRA_DEFINES =
EXTRA_CHKS =
DBG = 
OPT = -O
CC = gcc
ECHO = /bin/echo -e

include Makefile.common
