# This is for a MSYS2 version running on Windows. Last checked on Windows 11.
# Double click on buildtools.bat or buildtools-32.bat or mingw32.exe file in your toplevel MSYS2 directory.

HOST_CPU = 
DELIM = '
PiOS32 = 0
LINUX = 0
MSYS2 = 1
MINGW = 0
EXTRA_DEFINES = -DMSYS2
EXTRA_CHKS = -std=c99
DBG = 
OPT = -O2
CC = gcc
ECHO = echo
RM = rm -f 
RMDIR = rm -rf

include Makefile.common




