oldmac68 = 0	;Set this to 0 to test mac68-12.05 or older

.if eq,oldmac68
.nlist octal
.endc

.list mes
.radix 16
.dsabl ama

zpg == 55
abs == 6666
add == 1234
imm == 77
data == 44
port = 33
n = 0

.macro most68 op
	op #imm
	op i,imm
	op d,zpg
	op x,zpg
	op e,abs
	op zpg
.if eq,oldmac68
	op abs
	op fwd
.endc
.endm

.macro abxe op
.if eq,oldmac68
	op A
	op B
.endc
	op x,zpg
	op e,abs
.if eq,oldmac68
	op abs
.endc
.endm
.macro idxe op
.if eq,oldmac68
	op #zpg
.endc
	op i,zpg
	op i,-1
	op i,0ff
	op d,zpg
	op x,zpg
	op e,abs
.if eq,oldmac68
	op zpg
	op abs
.endc
.endm
.macro idxes op
	op #abs
	op i,abs
	op d,zpg
	op x,zpg
	op e,abs
.if eq,oldmac68
	op zpg
	op abs
.endc
.endm
.macro dxe op
	op zpg
	op d,zpg
	op x,zpg
	op e,abs
.if eq,oldmac68
	op abs
.endc
.endm
.macro abxe op
.if eq,oldmac68
	op a
	op b
.endc
	op x,zpg
	op e,abs
.if eq,oldmac68
	op zpg
.endc
.endm
.macro xe op
	op x,zpg
	op e,abs
	op zpg
.endm

    ABA    ;	00,		0x1B,	IMP	)		/* INHERENT */
    most68 ADCA    ;	00,		0x89,	MOST68	)		/* IMM, DIR, EXT, IND */
    most68 ADCB    ;	00,		0xC9,	MOST68	)		/* IMM, DIR, EXT, IND */
    most68 ADDA    ;	00,		0x8B,	MOST68	)		/* IMM, DIR, EXT, IND */
    most68 ADDB    ;	00,		0xCB,	MOST68	)		/* IMM, DIR, EXT, IND */
    most68 ANDA    ;	00,		0x84,	MOST68	)		/* IMM, DIR, EXT, IND */
    most68 ANDB    ;	00,		0xC4,	MOST68	)		/* IMM, DIR, EXT, IND */
    abxe ASL    ;	00,		0x48,	X|E|DES	)		/* EXT, IND */
    ASLA    ;	00,		0x48,	ACC	)		/* A */
    ASLB    ;	00,		0x58,	ACC	)		/* B */
    abxe ASR    ;	00,		0x47,	X|E|DES	)		/* EXT, IND */
    ASRA    ;	00,		0x47,	ACC	)		/* A */
    ASRB    ;	00,		0x57,	ACC	)		/* B */
bck:
    BCC bck    ;	00,		0x24,	S	)		/* REL */
    BCS bck   ;	00,		0x25,	S	)		/* REL */
    BEQ bck   ;	00,		0x27,	S	)		/* REL */
    BGE bck   ;	00,		0x2C,	S	)		/* REL */
    BGT bck   ;	00,		0x2E,	S	)		/* REL */
    BHI bck   ;	00,		0x22,	S	)		/* REL */
    most68 BITA    ;	00,		0x85,	MOST68	)		/* IMM, DIR, EXT, IND */
    most68 BITB    ;	00,		0xC5,	MOST68	)		/* IMM, DIR, EXT, IND */
    BLE fwd   ;	00,		0x2F,	S	)		/* REL */
    BLS fwd    ;	00,		0x23,	S	)		/* REL */
    BLT fwd   ;	00,		0x2D,	S	)		/* REL */
    BMI fwd   ;	00,		0x2B,	S	)		/* REL */
    BNE fwd   ;	00,		0x26,	S	)		/* REL */
    BPL fwd   ;	00,		0x2A,	S	)		/* REL */
    BRA fwd   ;	00,		0x20,	S	)		/* REL */
    BSR fwd   ;	00,		0x8D,	S	)		/* REL */
    BVC fwd   ;	00,		0x28,	S	)		/* REL */
    BVS fwd   ;	00,		0x29,	S	)		/* REL */
fwd:
    CBA    ;	00,		0x11,	IMP	)		/* INHERENT */
    CLC    ;	00,		0x0C,	IMP	)		/* INHERENT */
    CLI    ;	00,		0x0E,	IMP	)		/* INHERENT */
    abxe CLR    ;	00,		0x4F,	X|E|DES	)		/* EXT, IND */
    CLRA    ;	00,		0x4F,	ACC	)		/* A */
    CLRB    ;	00,		0x5F,	ACC	)		/* B */
    CLV    ;	00,		0x0A,	IMP	)		/* INHERENT */
    most68 CMPA    ;	00,		0x81,	MOST68	)		/* IMM, DIR, EXT, IND */
    most68 CMPB    ;	00,		0xC1,	MOST68	)		/* IMM, DIR, EXT, IND */
    abxe COM    ;	00,		0x43,	X|E|DES	)		/* EXT, IND */
    COMA    ;	00,		0x43,	ACC	)		/* A */
    COMB    ;	00,		0x53,	ACC	)		/* B */
    idxe CPX    ;	00,		0x8C,	MOST68|SPC	)	/* IMM, DIR, EXT, IND */
    DAA    ;	00,		0x19,	IMP	)		/* INHERENT */
    abxe DEC    ;	00,		0x4A,	X|E|DES	)		/* EXT, IND */
    DECA    ;	00,		0x4A,	ACC	)		/* A */
    DECB    ;	00,		0x5A,	ACC	)		/* B */
    DES    ;	00,		0x34,	IMP	)		/* INHERENT */
    DEX    ;	00,		0x09,	IMP	)		/* INHERENT */
    most68 EORA    ;	00,		0x88,	MOST68	)		/* IMM, DIR, EXT, IND */
    most68 EORB    ;	00,		0xC8,	MOST68	)		/* IMM, DIR, EXT, IND */
    abxe INC    ;	00,		0x4C,	X|E|DES	)		/* EXT, IND */
    INCA    ;	00,		0x4C,	ACC	)		/* A */
    INCB    ;	00,		0x5C,	ACC	)		/* B */
    INS    ;	00,		0x31,	IMP	)		/* INHERENT */
    INX    ;	00,		0x08,	IMP	)		/* INHERENT */
    xe JMP    ;	00,		0x4E,	X|E	)		/* EXT, IND */
    xe JSR    ;	00,		0x8D,	X|E	)		/* EXT, IND */
    most68 LDAA    ;	00,		0x86,	MOST68	)		/* IMM, DIR, EXT, IND */
    most68 LDAB    ;	00,		0xC6,	MOST68	)		/* IMM, DIR, EXT, IND */
.if eq,oldmac68
    idxes LDS    ;	00,		0x8E,	MOST68|SPC	)	/* IMM, DIR, EXT, IND */
    idxes LDX    ;	00,		0xCE,	MOST68|SPC	)	/* IMM, DIR, EXT, IND */
.endc
    abxe LSR    ;	00,		0x44,	X|E|DES	)		/* EXT, IND */
    LSRA    ;	00,		0x44,	ACC	)		/* A */
    LSRB    ;	00,		0x54,	ACC	)		/* B */
    abxe NEG    ;	00,		0x40,	X|E|DES	)		/* EXT, IND */
    NEGA    ;	00,		0x40,	ACC	)		/* A */
    NEGB    ;	00,		0x50,	ACC	)		/* B */
    NOP    ;	00,		0x01,	IMP	)		/* INHERENT */
    most68 ORAA    ;	00,		0x8A,	MOST68	)		/* IMM, DIR, EXT, IND */
    most68 ORAB    ;	00,		0xCA,	MOST68	)		/* IMM, DIR, EXT, IND */
    PSHA    ;	00,		0x36,	ACC	)		/* A */
    PSHB    ;	00,		0x37,	ACC	)		/* B */
    PULA    ;	00,		0x32,	ACC	)		/* A */
    PULB    ;	00,		0x33,	ACC	)		/* B */
    abxe ROL    ;	00,		0x49,	X|E|DES	)		/* EXT, IND */
    ROLA    ;	00,		0x49,	ACC	)		/* A */
    ROLB    ;	00,		0x59,	ACC	)		/* B */
    abxe ROR    ;	00,		0x46,	X|E|DES	)		/* EXT, IND */
    RORA    ;	00,		0x46,	ACC	)		/* A */
    RORB    ;	00,		0x56,	ACC	)		/* B */
    RTI    ;	00,		0x3B,	IMP	)		/* INHERENT */
    RTS    ;	00,		0x39,	IMP	)		/* INHERENT */
    SBA    ;	00,		0x10,	IMP	)		/* INHERENT */
    most68 SBCA    ;	00,		0x82,	MOST68	)		/* IMM, DIR, EXT, IND */
    most68 SBCB    ;	00,		0xC2,	MOST68	)		/* IMM, DIR, EXT, IND */
    SEC    ;	00,		0x0D,	IMP	)		/* INHERENT */
    SEI    ;	00,		0x0F,	IMP	)		/* INHERENT */
    SEV    ;	00,		0x0B,	IMP	)		/* INHERENT */
    dxe STAA    ;	00,		0x87,	D|X|E|DES	)	/* DIR, EXT, IND */
    dxe STAB    ;	00,		0xC7,	D|X|E|DES	)	/* DIR, EXT, IND */
    dxe STS    ;	00,		0x8F,	D|X|E|DES	)	/* DIR, EXT, IND */
    dxe STX    ;	00,		0xCF,	D|X|E|DES	)	/* DIR, EXT, IND */
    most68 SUBA    ;	00,		0x80,	MOST68	)		/* IMM, DIR, EXT, IND */
    most68 SUBB    ;	00,		0xC0,	MOST68	)		/* IMM, DIR, EXT, IND */
    SWI    ;	00,		0x3F,	IMP	)		/* INHERENT */
    TAB    ;	00,		0x16,	IMP	)		/* INHERENT */
    TAP    ;	00,		0x06,	IMP	)		/* INHERENT */
    TBA    ;	00,		0x17,	IMP	)		/* INHERENT */
    TPA    ;	00,		0x07,	IMP	)		/* INHERENT */
    abxe TST    ;	00,		0x4D,	X|E|DES	)		/* EXT, IND */
    TSTA    ;	00,		0x4D,	ACC	)		/* A */
    TSTB    ;	00,		0x5D,	ACC	)		/* B */
    TSX    ;	00,		0x30,	IMP	)		/* INHERENT */
    TXS    ;	00,		0x35,	IMP	)		/* INHERENT */
    WAI    ;	00,		0x3E,	IMP	)		/* INHERENT */

