;/* Common to all syntaxes:
; * Dn - data register
; * An - Address register
; * #d - immediate
; * d - absolute address (converted to pc relative if .enabl PC_RELATIVE)
; * r-r - register mask
; *
; * Atari syntax:
; * (An) - Address indirect
; * (An)+ - Address indirect, auto-increment
; * -(An) - auto-decrement, Adress indirect
; * d(An) - Address indirect + displacement
; * d(An,Dn) - Address indirect + displacement + index
; *
; * Motorola syntax:
; * (An) - Address indirect
; * (An)+ - Address indirect, auto-increment
; * -(An) - auto-decrement, Adress indirect
; * (d,An) - Address indirect + displacement
; * (d,An,Xn) - Adress indirect + displacement + index
; * (num).W or (num).L for forced word or long displacement
; *
; * MIT syntax (produced by gcc; but gcc also emits Motorola (like) syntax for some instructions):
; * An@ - Address indirect
; * An@- - Auto-decrement, address indirect
; * An@+ - Address indirect, auto-increment
; * Apc@(num) - Address indirect + displacement
; * Apc@(num,reg[:size]) - Index + displacement (optional size is one of w or l
; * num.W or num.L for forced word or long displacement
; * (Apc = any address register or PC)
; */

.list mes
.radix 16
.dsabl ama

zpg == 55
abs == 6666
add == 1234
imm == 77
data == 44
port = 33
n = 0

.macro OPDEF opcode class, val, bwl
.endm

; We only test the operand parser, not all instructions

	ADD.B #zpg,D0
	ADD.W #zpg,D1
	ADD.L #zpg,D2
	
	add.l d0,(a1)
	add.l d0,(a1)+
	add.l d0,-(a0)
	add.l d0,zpg(a0)
	add.l d0,abs(a0)
	add.l d0,zpg(a0,d0)
	add.l #imm,d0
	add.l #abs,d0
	add.l (a1),d0
	add.l (a1)+,d0
	add.l -(a0),d0
	add.l zpg(a0),d0
	add.l abs(a0),d0
	add.l zpg(a0,d0),d0

bck:
	nop
	bra bck
	bra.s bck
	bra fwd
	bra.s fwd
	nop
fwd:

	.word 1+2*3+1	; s/b 0xA
	.word 1+(2*3)+1	; s/b 0x8
	.word 1<<3		; s/b 0x8
	.word 100>>5	; s/b 0x8
	.word 1 == 2	; s/b 0
	.word 1 == 1	; s/b 1
	.word 1 != 2	; s/b 1
	.word 1 < 2		; s/b 1
	.word 1 > 2		; s/b 0
	.word 1 <= 2	; s/b 1
	.word 1 >= 2	; s/b 0

