	.list meb
	.nlist byt
	
OPCL_AU = 0
OPCL_LD = 1
OPCL_ST = 2
OPCL_BC = 3
OPCL_BS = 4
OPCL_JS = 5
OPCL_PS = 6
OPCL_IL = 7

reg = 0
.radix 10
.macro mkrg rg
  r'rg = %reg
  reg = reg+1
.endm
.rept 32
  mkrg \reg
.endr
.radix 16

.macro noc_def op1, op2, opc, num, dst
  .if eq,opc-OPCL_IL
    op1
	 .mexit
  .endc
  .if eq,opc-OPCL_BS
    op1 dst
	 .mexit
  .endc
  .if eq,opc-OPCL_PS
    op1 dst
	 .mexit
  .endc
  .error ;Did not handle op1
.endm

.macro br_def op1, op2, opc, num, dst
  .if eq, opc-OPCL_BS
    op1 r0,dst
  .iff
	 op1 dst
  .endc
.endm

.macro ls_def op1, op2, opc, num, oper
    op1 r0,r1[r2]
	 op2 r0,r1[r2]
    op1 r0,r1[oper]
    op2 r0,r1[oper]
.endm

.macro opcdef op1, op2, opc, num
	op1 r0, r1, r2
	op2 r0, r1, r2
.endm

	.word 1+2*3+1	; s/b 0xA
	.word 1+(2*3)+1	; s/b 0x8
	.word 1<<3		; s/b 0x8
	.word 100>>5	; s/b 0x8
	.word 1 == 2	; s/b 0
	.word 1 == 1	; s/b 1
	.word 1 != 2	; s/b 1
	.word 1 < 2		; s/b 1
	.word 1 > 2		; s/b 0
	.word 1 <= 2	; s/b 1
	.word 1 >= 2	; s/b 0

bck:
NOC_DEF   NOP ,  NOP.C , OPCL_IL,	0x08;	/* a NOP */
BR_DEF   BSP , BSP.C ,	OPCL_BC,	0, bck ;	/* Strictly Positive  ~N & ~Z, bck ; */
BR_DEF   BMZ , BMZ.C ,	OPCL_BC,	1, bck ;	/* Minus or Zero ~ ~N & ~Z, bck ; :  N | Z, bck ; */
BR_DEF   BGT , BGT.C ,	OPCL_BC,	2, bck ;
BR_DEF   BLE , BLE.C ,	OPCL_BC,	3, bck ;
BR_DEF   BGE , BGE.C ,	OPCL_BC,	4, bck ;
BR_DEF   BLT , BLT.C ,	OPCL_BC,	5, bck ;
BR_DEF   BHI , BHI.C ,	OPCL_BC,	6, bck ;	/*  unsigned > , bck ; */
BR_DEF   BLS , BLS.C ,	OPCL_BC,	7, bck ;	/* Low | same  unsigned <= , bck ; */
BR_DEF   BCC , BCC.C ,	OPCL_BC,	8, bck ;
BR_DEF   BLO , BLO.C ,	OPCL_BC,	8, bck ;	/*  unsigned < , bck ; aka BCC */
BR_DEF   BCS , BCS.C ,	OPCL_BC,	9, bck ;
BR_DEF   BHS , BHS.C ,	OPCL_BC,	9, bck ;	/* High | same  unsigned >= , bck ; aka BCS */
BR_DEF   BPL , BPL.C ,	OPCL_BC,	10, bck ;
BR_DEF   BMI , BMI.C ,	OPCL_BC,	11, bck ;
BR_DEF   BNE , BNE.C ,	OPCL_BC,	12, bck ;
BR_DEF   BEQ , BEQ.C ,	OPCL_BC,	13, bck ;
BR_DEF   BVC , BVC.C ,	OPCL_BC,	14, bck ;
BR_DEF   BVS , BVS.C ,	OPCL_BC,	15, bck ;
BR_DEF   BUGE , BUGE.C , OPCL_BC,	9, fwd ; /* aka HS, aka BCS */
BR_DEF   BUGT , BUGT.C , OPCL_BC,	6, fwd ; /* aka HI */
BR_DEF   BULE , BULE.C , OPCL_BC,	7, fwd ; /* aka LS */
BR_DEF   BULT , BULT.C , OPCL_BC,	8, fwd ; /* aka LO, aka BCC */
BR_DEF   BSR , BSR.C ,	OPCL_BS,	0x02, fwd ;	/* Also used for getpc */
BR_DEF   BRA , BRA.C ,	OPCL_BC,	0x02, fwd ;	/* BSR %0,target */

fwd:

LS_DEF   LEA , LEA.C ,	OPCL_LD,	0x03,	2 ; /* load effective  int; address */
LS_DEF   LEAS , LEAS.C ,OPCL_LD,	0x04,	1 ;
OPCDEF   SUBR , SUBR.C ,OPCL_AU,	0x05 ;
OPCDEF   XOR , XOR.C ,	OPCL_AU,	0x06 ;
OPCDEF   XORN , XORN.C ,OPCL_AU,	0x07 ;

OPCDEF   ADD , ADD.C ,	OPCL_AU,	0x08 ;
OPCDEF   SUB , SUB.C ,	OPCL_AU,	0x09 ;
OPCDEF   ADDC , ADDC.C ,OPCL_AU,	0x0A ;
OPCDEF   SUBC , SUBC.C ,OPCL_AU,	0x0B ;
OPCDEF   AND , AND.C ,	OPCL_AU,	0x0C ;
OPCDEF   ANDN , ANDN.C ,OPCL_AU,	0x0D ;
OPCDEF   OR , OR.C ,	OPCL_AU,	0x0E ;
OPCDEF   ORN , ORN.C ,	OPCL_AU,	0x0F ;

LS_DEF   LD , LD.C ,	OPCL_LD,	0x10,	2 ;
LS_DEF   LDS , LDS.C ,	OPCL_LD,	0x11,	1 ;
LS_DEF   LDUS , LDUS.C ,OPCL_LD,	0x12,	1 ;
LS_DEF   STS , STS.C ,	OPCL_ST,	0x13,	1 ;
LS_DEF   ST , ST.C ,	OPCL_ST,	0x14,	2 ;
LS_DEF   LDB , LDB.C ,	OPCL_LD,	0x15,	0 ;
LS_DEF   LDUB , LDUB.C ,OPCL_LD,	0x16,	0 ;
LS_DEF   STB , STB.C ,	OPCL_ST,	0x17,	0 ;

OPCDEF   ASHL , ASHL.C ,OPCL_AU,	0x1A ;
OPCDEF   ASHR , ASHR.C ,OPCL_AU,	0x18 ;
OPCDEF   LSHR , LSHR.C ,OPCL_AU,	0x19 ;
OPCDEF   SHL , SHL.C ,	OPCL_AU,	0x1A ;
OPCDEF   ROTL , ROTL.C ,OPCL_AU,	0x1B ;
NOC_DEF   GETPS , GETPS.C ,OPCL_PS,	0x1C, r15 ;
NOC_DEF   PUTPS , PUTPS.C ,OPCL_PS,	0x1D, r15 ;
LS_DEF   JSR , JSR.C ,	OPCL_JS,	0x1E,	2 ;

